sudo: required
services:
  - docker

before-install:
  - docker build -t konman01/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true konman01/react-test npm test

after_sucess:
  - docker build -t konman01/multi-client ./client
  - docker build -t konman01/multi-nginx ./nginx
  - docker build -t konman01/multi-server ./server
  - docker build -t konman01/multi-worker ./worker
  
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take those image and push to Docker huib
  - docker push konman01/multi-client
  - docker push konman01/multi-nginx
  - docker push konman01/multi-server
  - docker push konman01/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-west-2'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-west-2-040530867052'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY




